[programs.devnet]
breed = "FnHXok1nLqh5rVJLjseYx9WhtLWnXkRVBLaPjRH3i7rz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/fury/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
